apiVersion: batch/v1
kind: Job
metadata:
  generateName: after
  annotations:
    argocd.argoproj.io/hook: PostSync
  spec:
  template:
    metadata:
      name: curl-pod
    spec:
      containers:
      - name: curl-container
        image: alpine
        command: ["sh", "-c"]
        args:
        - apk update && apk add curl && curl http://my-backend-api.default.svc.cluster.local:8092/user/123 # Replace http://example.com with your desired URL
      restartPolicy: Never