apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  spec:
  template:
    metadata:
      name: curl-pod
    spec:
      containers:
      - name: curl-container
        image: alpine
        command: ["sh", "-c"]
        args:
        - apk update && apk add curl && curl http://my-backend-api:8092/user/123 # Replace http://example.com with your desired URL
      restartPolicy: Never