apiVersion: v1
kind: Service
metadata:
  name: my-backend-api
  labels:
    app: my-backend-api
spec:
  type: ClusterIP
  ports:
  - port: 8092
    protocol: TCP
    targetPort: 8092
  selector:
    app: my-backend-api